# Generated by Django 2.0.5 on 2018-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('display', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_date', models.DateTimeField(verbose_name='application occured date')),
                ('trans_date', models.DateTimeField(blank=True, null=True, verbose_name='transaction occured date')),
                ('trans_price', models.DecimalField(decimal_places=1, max_digits=9)),
                ('is_accept', models.NullBooleanField()),
                ('is_paid', models.NullBooleanField()),
                ('trans_composition', models.ForeignKey(on_delete=False, to='display.Composition')),
                ('trans_user', models.ForeignKey(on_delete=False, to='account.Commuser_relation')),
            ],
        ),
    ]
