# Generated by Django 2.0.5 on 2018-06-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='app_date',
            field=models.DateTimeField(verbose_name='application occured date'),
        ),
    ]
