# Generated by Django 2.0.5 on 2018-06-01 08:17

import display.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20180601_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_type', models.CharField(max_length=10)),
                ('upload_time', models.DateTimeField(verbose_name='uploaded time')),
                ('upload_path', models.FileField(upload_to=display.models.composition_directory_path)),
                ('upload_size', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(verbose_name='composition uploaded time')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('composition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='display.Composition')),
                ('origin', models.CharField(max_length=25)),
                ('abstractt', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=40)),
            ],
            bases=('display.composition',),
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('composition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='display.Composition')),
                ('patent_type', models.CharField(max_length=25)),
                ('patent_no', models.CharField(max_length=25)),
                ('apply_time', models.DateTimeField(verbose_name='patent applied time')),
                ('auth_time', models.DateTimeField(verbose_name='patent authorized time')),
            ],
            bases=('display.composition',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('composition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='display.Composition')),
                ('proj_type', models.CharField(max_length=25)),
                ('organization', models.CharField(max_length=25)),
                ('expense', models.IntegerField()),
                ('start_time', models.DateTimeField(verbose_name='project started time')),
                ('end_time', models.DateTimeField(verbose_name='project ended time')),
            ],
            bases=('display.composition',),
        ),
        migrations.AddField(
            model_name='composition',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Expertuser_realtion'),
        ),
        migrations.AddField(
            model_name='appendix',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Composition'),
        ),
    ]
