# Generated by Django 2.0.5 on 2018-06-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
    ]
