# Generated by Django 2.0.5 on 2018-06-09 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('display', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForHomepageClaiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('P', 'Passed'), ('S', 'Suspending'), ('R', 'Rejected')], max_length=1)),
                ('reject_reason', models.CharField(max_length=32)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Expertuser_relation')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.ExpertDetail')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationForRealNameCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('identity', models.CharField(max_length=18)),
                ('pic', models.ImageField(upload_to='realname/')),
                ('state', models.CharField(choices=[('P', 'Passed'), ('S', 'Suspending'), ('R', 'Rejected')], max_length=1)),
                ('reject_reason', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applicationforrealnamecertification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
