# Generated by Django 2.0.5 on 2018-06-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('que_id', models.AutoField(primary_key=True, serialize=False)),
                ('que_content', models.CharField(max_length=500)),
                ('que_date', models.DateTimeField(verbose_name='question occured date')),
                ('ans_content', models.CharField(max_length=500)),
                ('ans_date', models.DateTimeField(verbose_name='answered date')),
                ('ans_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_answer', to='account.Expertuser_relation')),
                ('que_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commuser_question', to='account.Commuser_relation')),
            ],
        ),
    ]
