# Generated by Django 2.0.5 on 2018-06-09 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commuser_relation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Expertuser_relation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=40)),
                ('identity', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('commuser_permission', 'permission design for common user'), ('expert_permission', 'permission design for expert'), ('service_permission', 'permission design for custom service'), ('verified_commuser_permission', 'permission desgin for verified common user'), ('verified_expert_permission', 'permission design for verified comm user')),
            },
        ),
        migrations.CreateModel(
            name='RealNameInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=40)),
                ('identity', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Study_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=30)),
            ],
        ),
    ]
