# Generated by Django 2.0.5 on 2018-06-03 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commuser_relation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Expertuser_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_register', models.BooleanField()),
                ('en_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=30)),
                ('inst_en_name', models.CharField(max_length=45)),
                ('inst_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Expertuser_relation')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='Study_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='institute',
            name='members',
            field=models.ManyToManyField(through='account.Membership', to='account.Expertuser_relation'),
        ),
        migrations.AddField(
            model_name='expertuser_relation',
            name='Study_area',
            field=models.ManyToManyField(to='account.Study_area'),
        ),
        migrations.AddField(
            model_name='expertuser_relation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
