# Generated by Django 2.0.5 on 2018-06-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='User_Permission',
        ),
    ]
