# Generated by Django 2.0.5 on 2018-06-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ans_expert',
        ),
        migrations.RemoveField(
            model_name='question',
            name='que_user',
        ),
        migrations.RemoveField(
            model_name='commuser_relation',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
